site_name: mkdocs-exam
site_description:
  !ENV [SITE_DESCRIPTION, "Mkdocs plugin to create training exams in markdown"]
site_author: !ENV [SITE_AUTHOR, "kjanat"]
site_url: !ENV [SITE_URL, CF_PAGES_URL, "http://localhost:8008"] # https://kjanat.github.io/gnk-examenvragen
copyright: Copyright &copy; 2025 - Kaj Kowalski

repo_name: !ENV [REPO_NAME, "kjanat/mkdocs-exam"]
repo_url: !ENV [REPO_URL, "https://github.com/kjanat/mkdocs-exam"]

edit_uri: edit/master/docs/

dev_addr: localhost:8008

nav:
  - Home: index.md
  - Disabled Exam: disable.md
  - Advanced: advanced.md

theme:
  name: material
  language: en

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search
  - mkdocs-exam
