repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        language_version: system
        files: "\\.(htm,html,css,js)$"
  - repo: https://github.com/standard/standard
    rev: v17.1.2
    hooks:
      - id: standard
        language_version: system
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.285
    hooks:
      - id: ruff
        args: [--fix]
