[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "mkdocs-exam"
version = "0.2.0"
description = "A mkdocs plugin to create an exam in your markdown document."
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [
  {name = "Kaj Kowalski", email = "dev+mkdocs-exam@kjanat.com"},
]

dependencies = [
  "mkdocs",
  "mkdocs-material",
]

[dependency-groups]
dev = [
  "ruff",
  "pre-commit",
  "pytest>=8.0",
  "pytest-cov>=4.0",
  "pytest-html>=4.0",
]

[project.urls]
homepage = "https://github.com/kjanat/mkdocs-exam"

[project.entry-points."mkdocs.plugins"]
"mkdocs-exam" = "mkdocs_exam.plugin:MkDocsExamPlugin"

[tool.setuptools.packages.find]
include = ["mkdocs_exam"]
exclude = ["example*", "assets*", "build*"]

[tool.setuptools.package-data]
"mkdocs_exam" = ["css/*", "js/*"]

[tool.ruff]
line-length = 120

[tool.pytest.ini_options]
minversion = "8.0"
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = [
  "-ra",
  "--strict-markers",
  "--strict-config",
  "--showlocals",
]

[tool.coverage.run]
source = ["mkdocs_exam"]
omit = [
  "*/tests/*",
  "*/__init__.py",
]

[tool.coverage.report]
precision = 2
show_missing = true
skip_covered = false
exclude_lines = [
  "pragma: no cover",
  "def __repr__",
  "raise AssertionError",
  "raise NotImplementedError",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
  "class .*\\bProtocol\\):",
  "@(abc\\.)?abstractmethod",
]
